---
title: "R Notebook"
output: html_notebook
---
```{r}
library(reactable)
library(htmltools)
library(readxl)
```




```{r}
# Set working directory
setwd("C:/Projects/PPE Phile/SDSN-SDG Indicators")

# Load data
data <- read_xlsx("data/SDR 2021 - Database.xlsx", sheet = "Overview")

country <- data[data$Country == "Finland", ]
reactable(country)
```


```{css, echo=FALSE}
/* Visually hide column headers, but keep them accessible to screen reader users. */
.hidden-column-headers .rt-thead {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  border: 0;
}

.table {
  border-left: 1px solid;
  border-bottom: 1px solid;
  display: table;
}

.tr {
  display: table-row;
}

.th, .td {
  border-top: 1px solid;
  border-right: 1px solid;
  padding: 4px 8px;
  display: table-cell;
}

.th {
  font-weight: bold;
}
.th[role="rowheader"] {
  background-color: lightgreen;
}
.th[role="columnheader"] {
  background-color: lightpink;
}
```


```{r}
#First row
reactable(
  data[1:1, 6:12],
  # Styling
#  showPageInfo = FALSE,
#  pagination = FALSE,
#  borderless = TRUE,
#
#  # Create Colun Groups
#  columnGroups = list(
#    colGroup(name = "SDG 1", columns = c("Goal 1 Dash", "Goal 1 Trend")),
#    colGroup(name = "SDG 2", columns = c("Goal 2 Dash", "Goal 2 Trend"))
#  ),
#  #columns = list(
#  #  #html tools
#  #  `Goal 1 Dash`= colDef(header = function(value) {
#  #    tags$a(display=FALSE)
#  #  })
#  #)
  class = "hidden-column-headers",
  sortable = FALSE
)
```

```{r}
iris
```

